<?php

/**
 * DocumentFamily.
 *
 * PHP version 7.2
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/*
 * PSB API 1.0.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace EConnect\Psb\Model;

/**
 * DocumentFamily Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class DocumentFamily
{
    /**
     * Possible values of this enum.
     */
    public const INVOICE = 'invoice';
    public const INVOICE_RESPONSE = 'invoiceResponse';
    public const REVIEW = 'review';
    public const ORDER = 'order';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INVOICE,
            self::INVOICE_RESPONSE,
            self::REVIEW,
            self::ORDER,
        ];
    }
}
